stages:
- build
- test
- release

build:
  image: dbogatov/docker-images:alpine-extras-latest
  stage: build
  script:
  - printf "%s" $(echo $CI_BUILD_REF | cut -c1-8) > version.txt
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - dist
  tags:
  - docker

put-resume:
  image: dbogatov/docker-images:alpine-extras-latest
  stage: build
  variables:
    GIT_STRATEGY: fetch
  script:
  - ./put-resume.sh "$TOKEN"
  artifacts:
    expire_in: 30 min
    paths:
    - dist/assets/custom/docs/resume.pdf
  tags:
  - docker

# tidy:
#   image: dbogatov/docker-images:tidy-latest
#   stage: test
#   variables:
#     GIT_STRATEGY: none
#   dependencies:
#   - build
#   # - put-resume
#   before_script:
#   - http-server dist/ -p 8080 > /dev/null &
#   - sleep 5
#   script:
#   - curl -Ls http://localhost:8080/home.html | tidy -e
#   - curl -Ls http://localhost:8080/academics.html | tidy -e
#   - curl -Ls http://localhost:8080/contacts.html | tidy -e
#   - curl -Ls http://localhost:8080/feedback.html | tidy -e
#   - curl -Ls http://localhost:8080/portfolio.html | tidy -e
#   - curl -Ls http://localhost:8080/resume.html | tidy -e
#   tags:
#   - docker
  
# blc:
#   image: dbogatov/docker-images:blc-latest
#   stage: test
#   variables:
#     GIT_STRATEGY: none
#   dependencies:
#   - build
#   - put-resume
#   before_script:
#   - http-server dist/ -p 8080 > /dev/null &
#   - sleep 5
#   script:
#   - blc --filter-level 3 --input http://localhost:8080/home.html -rog --exclude "*linkedin.*" | tee /dev/stderr | grep 'Finished!' | tail -1 | grep '0 broken.'
#   tags:
#   - docker

dockerify:
  stage: release
  dependencies:
  - build
  - put-resume
  script:
  - docker build -t registry.dbogatov.org/dbogatov/cv-website .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/cv-website
  tags:
  - shell

upload-bu:
  image: dbogatov/docker-images:alpine-extras-latest
  stage: release
  dependencies:
  - build
  - put-resume
  script:
  - mkdir -p ~/.ssh/
  - printf "%s\n" $BUKEY > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  # - cat ~/.ssh/id_rsa
  - cp dist/home.html dist/index.html
  - ssh -o StrictHostKeyChecking=no dmytro@csa1.bu.edu rm -rf /home/grad2/dmytro/public_html/*
  - scp -rp wwwroot/* dmytro@csa1.bu.edu:/home/grad2/dmytro/public_html/
  tags:
  - docker
