image: mhart/alpine-node

stages:
- build
- release

build:
  stage: build
  script:
#  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > version.json
  - apk add --update bash
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - wwwroot
  tags:
  - Docker

dockerify:
  stage: release
  dependencies:
  - build
  script:
  - docker build -t registry.dbogatov.org/dbogatov/cv-website .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/cv-website
  tags:
  - Shell