# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

before_script:
  - npm install
  - gulp

tidy:
  stage: test
  script:
  - tidy -config tidy.conf -e wwwroot/*.html
  only:
  - master