stages:
- build
- test
- release

build:
  image: larslarsson/alpine-node-sass
  stage: build
  script:
  - apk add --update bash
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - wwwroot
  tags:
  - docker

tidy:
  image: dbogatov/docker-images:tidy-latest
  stage: test
  dependencies:
  - build
  before_script:
  - http-server wwwroot/ -p 8080 > /dev/null &
  - sleep 5
  script:
  - curl -Ls http://localhost:8080/home.html | tidy -e
  - curl -Ls http://localhost:8080/academics.html | tidy -e
  - curl -Ls http://localhost:8080/contacts.html | tidy -e
  - curl -Ls http://localhost:8080/feedback.html | tidy -e
  - curl -Ls http://localhost:8080/portfolio.html | tidy -e
  - curl -Ls http://localhost:8080/resume.html | tidy -e
  tags:
  - docker
  
blc:
  image: dbogatov/docker-images:blc-latest
  stage: test
  dependencies:
  - build
  before_script:
  - http-server wwwroot/ -p 8080 > /dev/null &
  - sleep 5
  script:
  - blc --filter-level 3 --input http://localhost:8080/home.html -rog --exclude "*linkedin.*" | tee blc.out
  - "cat blc.out | grep '0 broken.'"
  tags:
  - docker

dockerify:
  stage: release
  dependencies:
  - build
  script:
  - docker build -t registry.dbogatov.org/dbogatov/cv-website .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/cv-website
  tags:
  - shell
