# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

tidy:
  type: test
  before_script:
  - npm install
  - gulp
  script:
  - tidy -config tidy.conf -e wwwroot/*.html
  only:
  - master
  
production:
  type: deploy
  script:
  - curl --request POST 'https://deploy.dbogatov.org/deploy' --data "token=$TOKEN" --data "project=CV-Website"
  only:
  - master
